# Generated by Django 4.0.10 on 2023-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
