# Generated by Django 4.0.10 on 2023-07-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
