# Generated by Django 4.0.10 on 2023-07-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
