# Generated by Django 4.0.10 on 2023-07-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
