# Generated by Django 3.2.4 on 2023-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
