# Generated by Django 4.0.10 on 2023-06-27 07:19

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roombooking_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.expressions.F('end'))), name='start_before_end'),
        ),
    ]
