# Generated by Django 4.0.10 on 2023-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_roombooking_start_before_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='bookingDeleteMsg',
            field=models.CharField(default='', max_length=256),
        ),
    ]
