# Generated by Django 4.0.10 on 2023-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roombooking_bookingdeletemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='bookingDeleteMsg',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
