# Generated by Django 4.0.10 on 2023-07-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_roombooking_bookingdeletemsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='bookingDeleteMsg',
        ),
    ]
