# Generated by Django 4.0.10 on 2023-07-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_deletebookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteBookingModel',
        ),
    ]
